Add "template" module
google/chicago-brick pull request #401
Opened 2023-02-08 22:21 UTC by g-harel

I thought it would be nice to have a base module that contains the entirety of the API for contributors. Especially since the load functions look like they're being slurped and their arguments are being injected with reflection.

This doesn't work right now because `wallGeometry` is undefined in `willBeShownSoon`, but I wanted to get your initial feedback on the bones and see if this is a mergeable idea.

2023-02-09 06:44 UTC, applmak requested changes

2023-02-09 06:44 UTC, applmak commented on demo_modules/_template/brick.json
> +  }
add testonly so that this module doesn't get added to any collections by default.

2023-02-09 06:44 UTC, applmak commented on demo_modules/_template/template_client.ts
> +  _debug: Logger,
Remove the _, because if this stands as a template, people will think you should leave them in!

2023-02-09 06:44 UTC, applmak commented on demo_modules/_template/template_client.ts
> +  _debug: Logger,
(just disable the lint errors as needed)

2023-02-09 06:44 UTC, applmak commented on demo_modules/_template/template_server.ts
> +  _assert: typeof libAssert,
Ditto about _

2023-02-09 06:44 UTC, applmak commented on demo_modules/_template/template_server.ts
> +  _assert: typeof libAssert,
Assert can be simply imported now and shouldn't be injected.

2023-02-09 06:44 UTC, applmak commented on demo_modules/_template/template_client.ts
> +  _debug: Logger,
Debug should be imported now and no longer injected

2023-02-09 06:44 UTC, applmak commented on demo_modules/_template/template_server.ts
> +  _debug: Logger,
Debug should be imported now and no longer injected.

2023-02-14 16:17 UTC, applmak commented
This lgtm. You probably want to git rebase -i @~5 and fold these into one or two commits. However, this is also fine as is

2023-02-14 16:17 UTC, applmak approved these changes
Lgtm

2023-02-14 17:47 UTC, merged

2023-02-14 17:47 UTC, g-harel commented
I squashed them into one commit before merging!